### ISSUE TITLE
database file is missing

### ISSUE THREAD

**Issue by lagkdok** [hasan-py/CMS-with-PHP-Mysql#1]
hi,
i've just download the cms but there is no database file to connect it with the script
thanks

**Comment by lagkdok** [comment]
still waiting for database file sql please

**Comment by lagkdok** [comment]
I'm always still waiting for the sql file please, we can't test the script without the database file.

**Comment by hasan-py** [comment]
sorry for late reply ..

**Comment by hasan-py** [comment]
Extremely sorry about that. Please check the repo now. I committed database file.

**Comment by hasan-py** [comment]
And it have also some bug. I didn't  fixed it. Because I work in another project. So hope you fixed the bugs. Bug will be show in Edit user in admin, where password not hashed. So when you going to edit user account and edit your profile the password will maybe crashed i am not sure about that. Just check those thing.

**Comment by hasan-py** [comment]
And it have also some bugs in sidebar: category Ui, 
I didn't fixed it. Because I work in another project. So hope you will fixed it. Bug will be show in front end category sidebar, when you add category & when you go to category based post page. This problem heppend for the templates. So you need to edit that.
N.B: Password Edit option not implement in admin panel.

**Comment by hasan-py** [comment]
And it have also some bugs in Front end : sidebar,category Ui, 
I didn't fixed it. Because I work in another project. So hope you will fixed it. Bug will be show in front end category sidebar, when you add category & when you go to category based post page. This problem heppend for the templates. So you need to edit that.
I fixed all necessary issues. Now this is a fresh project Just clone it and enjoy.
N.B: Password Edit features not implement in admin panel.

**Comment by hasan-py** [comment]
Please Check the repo now.

**Comment by lagkdok** [comment]
I did thank you; I'm working on it now

**Comment by hasan-py** [comment]
Okay. My pleasure.

**Comment by hasan-py** [comment]
Your welcome.
